-- Creación de las tablas
CREATE TABLE LINEA
( id INTEGER PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  color TEXT NOT NULL,
  start TEXT NOT NULL,
  end  TEXT NOT NULL,
  express BOOLEAN NOT NULL );

CREATE TABLE ESTACION
( id INTEGER PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  linea INTEGER NOT NULL REFERENCES LINEA(id),
  position TEXT);

CREATE TABLE HORARIO
( id INTEGER PRIMARY KEY NOT NULL,
  estacion INTEGER NOT NULL REFERENCES ESTACION(id),
  type INTEGER NOT NULL,
  open INTEGER,
  close INTEGER,
  first_start INTEGER,
  last_start INTEGER,
  first_end INTEGER,
  last_end INTEGER);


